<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );
require_once("$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php");

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "Gramene Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
# $wgServer      = "http://gwiki.gramene.org";
# $wgServername  = "ascutney.cshl.edu";
$wgScriptPath       = "/gramene-wiki";
#$wgScriptPath       = "/";
$wgScriptExtension  = ".php";
$wgArticlePath      = "/$1";
$wgUsePathInfo      = "false";
$wgVerifyMimeType   = false;
$wfFavicon          = "$wgScriptPath/favicon.ico";

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableEmail      = true;
$wgEnableUserEmail  = true;

$wgEmergencyContact = "shiran@cshl.edu";
$wgPasswordSender = "shiran@cshl.edu";

## For a detailed description of the following switches see
## http://www.mediawiki.org/wiki/Extension:Email_notification 
## and http://www.mediawiki.org/wiki/Extension:Email_notification
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

$wgDBtype           = "mysql";
$wgDBserver         = "localhost:/var/lib/mysql/mysql.sock";
$wgDBname           = "wikidb";
$wgDBuser           = "wikiuser";
$wgDBpassword       = "w1k14EvAh";

# MySQL specific settings
$wgDBprefix         = "gramene_";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "TYPE=InnoDB";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

# Postgres specific settings
$wgDBport           = "5432";
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

$wgFileExtensions = array('ppt', 'doc', 'dot', 'png', 'jpg', 'jpeg', 'gif', 'xls', 'pdf', 'html', 'enl', 'txt', 'docx', 'pptx', 'dotx', 'rtf', 'eps', 'ico', 'svg');

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUploadDirectory     = "{$IP}/uploads";
$wgUploadPath = "{$wgScriptPath}/img_auth.php";
# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

$wgLogo  = "$wgScriptPath/images/gramene-wiki-logo.png";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "6f94434e4db08d8bdaa8a139d7ac1cd1e20a54898292711be397689865e7635b";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.


# No anonymous access 
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['user']['createaccount'] = true; # allow existing users to create new ones.  
$wgGroupPermissions['*']['edit'] = false;
$wgWhitelistRead = array("Special:Userlogin", "-" );
$wgGroupPermissions['*']['read'] = false;
$wgShowIPinHeader = false; # For non-logged in users
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

require_once('extensions/googleCalendar.php');
require_once('extensions/articletocategory.php');
#require_once('extensions/FCKeditor/FCKeditor.php')
require_once('extensions/StubManager/StubManager.php');
require_once('extensions/Gravatar/Gravatar.php');
require_once('extensions/Cite/Cite.php');
require_once('extensions/inputbox/inputbox.php');
require_once('extensions/ToggleDisplay/ToggleDisplay.php');

?>
